"""Investigation input and result schemas for AI-assisted SOC triage.

Security & Untrusted Data Boundary:
All telemetry attributes (such as logs, command_line, decoded_command, user, host,
and retrieved artifacts) must be treated strictly as UNTRUSTED DATA. They must never
be treated as instructions, evaluated as code, or used to alter tool routing or policy
enforcement logic.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional, Sequence, Tuple, Union


class SchemaValidationError(ValueError):
    """Raised when an investigation schema invariant is violated."""
    pass


class ConfidenceLevel(str, Enum):
    """Deterministic confidence rating for an investigation hypothesis."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


ALLOWED_CONFIDENCE_LEVELS = frozenset({"low", "medium", "high"})


@dataclass(frozen=True)
class InvestigationInput:
    """Immutable input schema capturing alert context for investigation.

    All fields are mandatory, non-empty strings representing the telemetry record
    that triggered the alert.
    """
    incident_id: str
    timestamp: str
    host: str
    user: str
    image: str
    command_line: str
    parent_image: str
    parent_command_line: str
    detection_name: str
    detection_id: str

    def __post_init__(self) -> None:
        """Validate that all fields are non-empty strings."""
        required_fields = (
            "incident_id",
            "timestamp",
            "host",
            "user",
            "image",
            "command_line",
            "parent_image",
            "parent_command_line",
            "detection_name",
            "detection_id",
        )
        for field in required_fields:
            val = getattr(self, field)
            if type(val) is not str:
                raise SchemaValidationError(
                    f"Field '{field}' must be a str, got {type(val).__name__}"
                )
            if not val.strip():
                raise SchemaValidationError(
                    f"Field '{field}' cannot be empty or whitespace-only"
                )


@dataclass(frozen=True)
class InvestigationResult:
    """Structured, deeply immutable output record generated by an investigation workflow.

    Collections (observations, mitre_techniques, suspicious_indicators, evidence_refs)
    are normalized to immutable tuples of non-empty strings.
    """
    summary: str
    observations: Union[Tuple[str, ...], Sequence[str]]
    decoded_command: Optional[str]
    mitre_techniques: Union[Tuple[str, ...], Sequence[str]]
    suspicious_indicators: Union[Tuple[str, ...], Sequence[str]]
    recommended_next_step: str
    confidence_level: str
    evidence_refs: Union[Tuple[str, ...], Sequence[str]]

    def __post_init__(self) -> None:
        """Validate required output fields, confidence levels, and normalize collections to tuples."""
        if type(self.summary) is not str or not self.summary.strip():
            raise SchemaValidationError("Field 'summary' must be a non-empty string")

        if type(self.recommended_next_step) is not str or not self.recommended_next_step.strip():
            raise SchemaValidationError(
                "Field 'recommended_next_step' must be a non-empty string"
            )

        if self.confidence_level not in ALLOWED_CONFIDENCE_LEVELS:
            raise SchemaValidationError(
                f"Invalid confidence_level '{self.confidence_level}'. Allowed: {sorted(ALLOWED_CONFIDENCE_LEVELS)}"
            )

        if self.decoded_command is not None:
            if type(self.decoded_command) is not str or not self.decoded_command.strip():
                raise SchemaValidationError(
                    "Field 'decoded_command' must be None or a non-empty string"
                )

        # Validate and normalize each collection field to an immutable tuple
        collection_fields = (
            "observations",
            "mitre_techniques",
            "suspicious_indicators",
            "evidence_refs",
        )
        for field in collection_fields:
            raw_val = getattr(self, field)
            if not isinstance(raw_val, (list, tuple)):
                raise SchemaValidationError(
                    f"Field '{field}' must be a list or tuple of strings, got {type(raw_val).__name__}"
                )

            # Per-element validation: every item must be non-empty string exactly
            validated_elements = []
            for idx, elem in enumerate(raw_val):
                if type(elem) is not str:
                    raise SchemaValidationError(
                        f"Element at index {idx} in '{field}' must be str, got {type(elem).__name__}"
                    )
                if not elem.strip():
                    raise SchemaValidationError(
                        f"Element at index {idx} in '{field}' cannot be empty or whitespace-only"
                    )
                validated_elements.append(elem)

            # Convert to deeply immutable tuple
            object.__setattr__(self, field, tuple(validated_elements))
